services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    networks:
      - proyecto
    volumes:
      - mysql_data:/var/lib/mysql
  api:
    build: .
    container_name: api_container
    depends_on:
      - mysql
    env_file:
      - ./.env
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    networks:
      - proyecto
    restart: "no"

networks:
  proyecto:
volumes:
  mysql_data: